---
title: "Çalışmanızın Başlığı"
author: 
  - Akın Aydın[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 21080197, [Github Repo](https://github.com/AkinAyd/AraSinav)

# Giriş
Mutluluk, insanların doğumdan ölüme kadar ençoklamaya (maksimize etmeye) çalıştığı temel unsurlardan biridir. Bu bağlamda mutluluk, birçok sosyal bilimcinin üzerinde çalıştığı konulardan biri olmuştur. Literatüre farklı kavramlar ve analiz çeşitleri de zaman içinde eklenmiştir.

Çalışma seçilmiş ülkelerin 2018 yılından elde edilmiş ulusal verileri ile yürütülmektedir. Çalışmada gelir dağılımı (Gini endeksi), yıllık kişi başı milli gelir, özgürlük mertebesi, hukuka bağlılık, ülkede baskın olan dini inanç, mutluluk, toplam nüfus, eğitim seviyesi, insan sermayesi endeksi, reel gayrisafi yurtiçi hasıla ve işsizlik oranı değişkenleri kullanılmıştır. Mutluluk bağımlı değişken olmakla beraber kalan değişkenler bağımsız değişken olarak değerlendirilmiştir. Ülkede baskın olan dini inanç ve özgürlük mertebesi kategorik değişkenler iken kalan değişkenler sayısal değişkenlerdir. Sayısal değişkenler arasında regresyon analizi ve kategorik değişkenler arasında korelasyon analizi yapılması öngörülmektedir. Gözlem olarak düşük gelirli, düşük-orta gelirli, yüksek-orta gelirli ve yüksek gelirli ülkeler arasından 50 adet ülke seçilmiştir.

## Çalışmada Kullanılan Veri
Çalışmada kullanılan veri çeşitli kaynaklardan toplanmıştır. Mutluluk endeksini elde etmek için [World Happiness Report](https://worldhappiness.report), dini verileri elde etmek için [ARDA](https://www.thearda.com), özgürlük hakkında veriler elde etmek için [Freedom House](https://freedomhouse.org), hukuka bağlılık hakkında veriler elde etmek için [World Justice Project](https://worldjusticeproject.org) ve kalan verileri elde etmek için de (toplam nüfus, gini endeksi, insan sermayesi endeksi, yıllık kişi başı milli gelir, reel gayrisafi yurtiçi hasıla, işsizlik oranı) [World Bank](https://data.worldbank.org) kullanılmıştır.

## Çalışmanın Amacı
Çalışma, genel anlamda insanları anlamak ve toplumdaki mutluluğu maksimize etmek isteyen bir hükümetin yapması gerekenlere ışık tutması açısından önem arz etmektedir.Büyüme yanlısı politikaların insanları gerçekten memnun edip etmediği konuları tartışılmaktadır.

Bu çalışma ile ulaşılmaya çalışılan hedef, mutluluğun gelir ile pozitif bir ilişki içerisinde olup olmadığı ve -varsa- mutluluğu açıklayan alternatif değişkenlerin neler olabileceği gibi sorulara anlamlı cevaplar verebilmektir.

## Literatür 
Gelir ile mutluluk arasındaki ilişkinin test edilmeye başlanması ilk olarak @easterlin1974does çalışması ile görülmüştür. Bu çalışmada Easterlin, yatay kesit verilerin zaman serisi verilerine göre daha kuvvetli bir ilişki içerisinde olduğunu öne sürmüştür. Yani göreli gelirin (içinde bulunulan topluma kıyasla elde edilen gelir) mutlak gelire göre mutluluk ile daha yüksek bir korelasyona sahip olduğundan bahsetmiştir. @easterlin1995will çalışmasında "Hepimizin geliri aynı anda artsa hepimizin mutluluğu aynı anda mı artacak?" sorusunu sormuş ve göreli gelirin önemini bir kez daha vurgulamıştır. Bu çalışmalardan elde edilen sonuçla, kısa dönemde mutluluğun mutlak gelir ile pozitif bir ilişki içerisinde olup, uzun dönemde gelirin artmasına rağmen mutluluğun artmaması literatürde "Easterlin Paradoksu" adını almıştır. Örnek vermek gerekirse, @frank2012easterlin çalışmasında 2. Dünya savaşı sonrası hızla büyüyen Japonya için yaptığı zaman serisi analizi verilebilir. Çalışma, büyümenin uzun yıllar boyunca hızla artmasına rağmen mutlulukta bir artış olmadığını göstermektedir.

Richard Easterlin'in çalışmalarında ulaşılan sonuçlara en büyük itiraz Betsey Stevenson ve Justin Wolfers tarafından gelmiştir. @stevenson2008economic Easterlin'in yatay kesit analizlerinin yüksek hacimli ve kaliteli veri içerdiği, fakat ülkelerin kıyaslandığı zaman serisi analizlerinde kullanılan gözlem hacminin yeteri kadar büyük olmadığından ve "Easterlin Paradoksu" kavramının istatistiki bir hatadan ibaret olduğundan bahsetmişlerdir. @stevenson2008economic çalışmasında yatay kesit analizlerinde gözlemlenen pozitif ilişkinin yanında zaman serisi analizlerinde de pozitif bir ilişki gözlemlediklerini, ülkelerin zaman içerisinde artan gelir ile mutluluğunun aynı yönde değiştiğini, dolayısıyla önemli olan unsurun bireyin mutlak geliri olduğundan bahsetmişlerdir. Bu bağlamda farklı analiz çeşitlerinin nasıl ve ne şekilde ortaya çıktığını gözlemlemek mümkün.

### Mutlak Gelir ve Mutluluk İlişkisinin Bir Eşiği Var Mı?
@layard2003happiness çalışmasında "Bir ülke yıllık 15000$ kişi başı gelir üzerine çıktığı zaman gelir ile mutluluk birbirinden bağımsızdır" söyleminde bulunmuş ve mutlak gelirin belirli bir gelir eşiğine kadar mutluluğun bir unsuru olduğunu vurgulamıştır. Yaptığı çalışmalar sonucu insanların birbirleri içinde rekabet halinde olduğu bu yüzden de göreli gelirin daha önemli olduğu kanısına varmıştır. @layard2006happiness çalışmasında her bireyin elde ettiği gelir diğer bireyin üzerinde negatif dışsallık yaratacağı için yüksek gelir ve tüketim vergilerini bir çözüm olarak öne sürmüştür. Buna karşın @deaton2008income çalışmasında en zengin ülkelerde bile daha fazla gelirin daha fazla mutluluğa yol açtığını, sadece marjinal faydasının azaldığını gözlemlemiştir. Dolayısıyla Deaton ve Layard'ın vardığı sonuçlar tamamen çelişmektedir.




\newpage
# Kaynakça {#references}
<div id="refs"></div>

